# Generated by Django 5.2.11 on 2026-03-19 18:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_badge', models.CharField(blank=True, help_text='Identifiant unique du badge employé (ex: AMN-2025-001)', max_length=20, null=True, unique=True, verbose_name='ID Badge')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Photo de profil')),
                ('department', models.CharField(choices=[('TECH', 'Technology & IT'), ('FINANCE', 'Finance & Accounting'), ('HR', 'Human Resources'), ('OPS', 'Operations'), ('MKT', 'Marketing & Communications'), ('LEGAL', 'Legal & Compliance'), ('SALES', 'Sales & Business Development'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='Département')),
                ('country', models.CharField(choices=[('CM', 'Cameroon'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('SN', 'Senegal'), ('CI', "Côte d'Ivoire"), ('CD', 'DR Congo'), ('MZ', 'Mozambique'), ('MG', 'Madagascar'), ('XX', 'Other')], default='CM', max_length=2, verbose_name='Pays')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Poste / Titre')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue préférée')),
                ('is_verified', models.BooleanField(default=False, help_text="True si l'adresse email a été confirmée", verbose_name='Email vérifié')),
                ('verification_code', models.CharField(blank=True, max_length=6, verbose_name='Code de vérification')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Code créé le')),
                ('is_frozen', models.BooleanField(default=False, help_text='Compte en attente de suppression définitive', verbose_name='Compte gelé')),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, help_text='Date de suppression définitive (J+30 après demande)', null=True, verbose_name='Suppression programmée le')),
                ('deletion_cancel_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token annulation suppression')),
                ('password_reset_token', models.UUIDField(blank=True, null=True, verbose_name='Token réinitialisation MDP')),
                ('password_reset_token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Token MDP créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('register', 'Inscription'), ('email_verified', 'Email vérifié'), ('password_changed', 'Mot de passe modifié'), ('password_reset_req', 'Demande réinitialisation MDP'), ('account_frozen', 'Compte gelé'), ('account_restored', 'Compte restauré'), ('account_deleted', 'Compte supprimé'), ('profile_updated', 'Profil mis à jour'), ('failed_login', 'Tentative de connexion échouée')], max_length=30, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Informations contextuelles au format JSON', verbose_name='Données supplémentaires')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['id_badge'], name='users_emplo_id_badg_1466d7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'country'], name='users_emplo_departm_c81866_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_frozen', 'deletion_scheduled_at'], name='users_emplo_is_froz_0bab1a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'action'], name='users_activ_user_id_0b9d76_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='users_activ_timesta_22698c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address'], name='users_activ_ip_addr_d9dd69_idx'),
        ),
    ]
