# Generated by Django 5.2.11 on 2026-03-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_has_seen_inventory_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_seen_learning_tour',
            field=models.BooleanField(default=False, help_text="True si l'employé a déjà vu le tutoriel interactif du module Learning", verbose_name='Tour guidé Learning vu'),
        ),
    ]
