# Generated by Django 5.2.11 on 2026-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_has_seen_learning_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_seen_warehouse_tutorial',
            field=models.BooleanField(default=False, help_text="True si l'employé a déjà vu le tutoriel de la page Entrepôt", verbose_name='Tutoriel entrepôt vu'),
        ),
    ]
