# Generated by Django 5.2.12 on 2026-03-21 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_amn",
                    models.CharField(
                        help_text="Identifiant unique du matériel (ex: AMN-IT-2025-001)",
                        max_length=30,
                        unique=True,
                        verbose_name="Tag AMN",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Désignation")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LAPTOP", "Ordinateur portable"),
                            ("DESKTOP", "Ordinateur fixe"),
                            ("PHONE", "Téléphone"),
                            ("TABLET", "Tablette"),
                            ("MONITOR", "Écran"),
                            ("PRINTER", "Imprimante"),
                            ("VEHICLE", "Véhicule"),
                            ("NETWORK", "Équipement réseau"),
                            ("FURNITURE", "Mobilier"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=80, verbose_name="Marque"),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Modèle"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Numéro de série",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("ASSIGNED", "Attribué"),
                            ("IN_REPAIR", "En réparation"),
                            ("RETIRED", "Retraité"),
                            ("LOST", "Perdu / Volé"),
                        ],
                        default="AVAILABLE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'attribution"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'achat"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Prix d'achat (FCFA)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "qr_code_data",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Données QR Code"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attribué à",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actif",
                "verbose_name_plural": "Actifs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transferred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date du transfert",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="inventory.asset",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "from_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="De",
                    ),
                ),
                (
                    "to_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_in",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vers",
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_managed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectué par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert d'actif",
                "verbose_name_plural": "Transferts d'actifs",
                "ordering": ["-transferred_at"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Désignation")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Catégorie"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Référence / SKU"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité en stock"
                    ),
                ),
                (
                    "alert_threshold",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Notification envoyée quand la quantité atteint ce seuil",
                        verbose_name="Seuil d'alerte",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="unité", max_length=20, verbose_name="Unité"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Emplacement"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Fournisseur"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Article de stock",
                "verbose_name_plural": "Articles de stock",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="inventory_s_categor_228d77_idx"
                    ),
                    models.Index(
                        fields=["quantity", "alert_threshold"],
                        name="inventory_s_quantit_19ee75_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "Entrée stock"), ("OUT", "Sortie stock")],
                        max_length=3,
                        verbose_name="Type",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "quantity_before",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité avant"
                    ),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité après"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence (bon de commande, facture…)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Horodatage",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.stockitem",
                        verbose_name="Article",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectué par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de ticket",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Sujet")),
                (
                    "description",
                    models.TextField(verbose_name="Description du problème"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tickets/%Y/%m/",
                        verbose_name="Photo de la panne",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Haute"),
                            ("CRITICAL", "Critique / SOS"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouvert"),
                            ("IN_PROGRESS", "En cours"),
                            ("RESOLVED", "Résolu"),
                            ("CLOSED", "Fermé"),
                        ],
                        default="OPEN",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Note interne"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="inventory.asset",
                        verbose_name="Actif concerné",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Soumis par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket support",
                "verbose_name_plural": "Tickets support",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["tag_amn"], name="inventory_a_tag_amn_2d4c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["status", "category"], name="inventory_a_status_0d3db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["assigned_to"], name="inventory_a_assigne_84c795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["item", "timestamp"], name="inventory_s_item_id_b1cdaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["transaction_type", "timestamp"],
                name="inventory_s_transac_1dac81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "priority"], name="inventory_t_status_b001b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["submitted_by", "created_at"],
                name="inventory_t_submitt_4ce21c_idx",
            ),
        ),
    ]
