# Generated by Django 5.2.11 on 2026-03-20 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du parcours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target_department', models.CharField(help_text='Code département (ex: TECH, HR, FINANCE...)', max_length=10, verbose_name='Département cible')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='learning/paths/', verbose_name='Miniature')),
                ('estimated_hours', models.PositiveIntegerField(default=0, verbose_name='Durée estimée (heures)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcours de formation',
                'verbose_name_plural': 'Parcours de formation',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_multiple_choice', models.BooleanField(default=False, help_text='Si True, plusieurs réponses peuvent être correctes', verbose_name='Choix multiple')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BuddyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'assignation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('buddy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_employees', to=settings.AUTH_USER_MODEL, verbose_name='Parrain / Buddy')),
                ('new_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_assignment', to=settings.AUTH_USER_MODEL, verbose_name='Nouvel employé')),
            ],
            options={
                'verbose_name': 'Assignation Buddy',
                'verbose_name_plural': 'Assignations Buddy',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='learning.learningpath', verbose_name='Parcours')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la leçon')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('TEXT', 'Texte'), ('PDF', 'PDF')], default='TEXT', help_text='VIDEO masqué en mode Low-Data', max_length=10, verbose_name='Type de contenu')),
                ('media_url', models.URLField(blank=True, help_text='URL YouTube/Vimeo pour VIDEO, URL audio pour AUDIO', verbose_name='URL média')),
                ('content_text', models.TextField(blank=True, help_text='Contenu texte riche (markdown supporté)', verbose_name='Contenu texte')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='learning/pdfs/', verbose_name='Fichier PDF')),
                ('duration_minutes', models.PositiveIntegerField(default=5, verbose_name='Durée estimée (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_journey', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': "Parcours d'intégration",
                'verbose_name_plural': "Parcours d'intégration",
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text="Nombre de jours depuis le début de l'intégration avant déblocage", verbose_name='Jour de déblocage')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'étape")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='📋', max_length=10, verbose_name='Icône emoji')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='learning.onboardingjourney', verbose_name='Parcours')),
            ],
            options={
                'verbose_name': "Étape d'intégration",
                'verbose_name_plural': "Étapes d'intégration",
                'ordering': ['day_number'],
                'unique_together': {('journey', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('READ', 'Lecture'), ('WATCH', 'Vidéo'), ('MEET', 'Rencontre'), ('ACTION', 'Action')], default='READ', max_length=10, verbose_name='Type de tâche')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu / Instructions')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('meet_colleague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meet_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Collègue à rencontrer')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.onboardingstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': "Tâche d'intégration",
                'verbose_name_plural': "Tâches d'intégration",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texte du choix')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du quiz')),
                ('passing_score_percentage', models.PositiveIntegerField(default=70, help_text='Pourcentage minimum pour réussir (0-100)', verbose_name='Score minimum (%)')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Tentatives maximum')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learning.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percentage', models.FloatField(default=0, verbose_name='Score obtenu (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('answers', models.JSONField(default=dict, help_text='{"question_id": [choice_id, ...], ...}', verbose_name='Réponses soumises')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tentative le')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Délivré le')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='learning/certificates/', verbose_name='Fichier PDF')),
                ('unique_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code unique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='learning.learningpath', verbose_name='Parcours')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'unique_together': {('user', 'path')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Complétée')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complétée le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='learning.onboardingtask', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Complétion de tâche',
                'verbose_name_plural': 'Complétions de tâches',
                'unique_together': {('employee', 'task')},
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inscrit le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.learningpath', verbose_name='Parcours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('user', 'path')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Complétée')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complétée le')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Temps passé (secondes)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.lesson', verbose_name='Leçon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'indexes': [models.Index(fields=['user', 'is_completed'], name='learning_us_user_id_6a6847_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
