# Generated by Django 5.2.12 on 2026-03-20 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                ("total_employees", models.PositiveIntegerField(default=0)),
                ("present_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("absent_count", models.PositiveIntegerField(default=0)),
                ("suspicious_count", models.PositiveIntegerField(default=0)),
                (
                    "report_data",
                    models.JSONField(default=dict, verbose_name="Données détaillées"),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rapport de présence",
                "verbose_name_plural": "Rapports de présence",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom du site")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Adresse"
                    ),
                ),
                (
                    "country",
                    models.CharField(default="CM", max_length=2, verbose_name="Pays"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="ex: 3.8480 pour Yaoundé", verbose_name="Latitude GPS"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="ex: 11.5021 pour Yaoundé",
                        verbose_name="Longitude GPS",
                    ),
                ),
                (
                    "allowed_radius_meters",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Distance maximale depuis le bureau pour pointer (défaut : 200m)",
                        verbose_name="Rayon autorisé (mètres)",
                    ),
                ),
                (
                    "check_in_start_hour",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Heure à partir de laquelle le pointage est autorisé (ex: 6 → 06:00)",
                        verbose_name="Heure d'ouverture pointage",
                    ),
                ),
                (
                    "check_in_end_hour",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Heure limite pour pointer (ex: 12 → 12:00)",
                        verbose_name="Heure de fermeture pointage",
                    ),
                ),
                (
                    "late_after_hour",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Un pointage après cette heure est marqué EN RETARD",
                        verbose_name="Retard après (heure)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Site AMN",
                "verbose_name_plural": "Sites AMN",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        help_text="Hash SHA-256 des caractéristiques de l'appareil",
                        max_length=64,
                        verbose_name="Empreinte appareil",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent abrégé pour identification visuelle",
                        max_length=200,
                        verbose_name="Nom de l'appareil",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Premier pointage",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Dernier pointage",
                    ),
                ),
                (
                    "is_trusted",
                    models.BooleanField(default=True, verbose_name="Approuvé"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil enregistré",
                "verbose_name_plural": "Appareils enregistrés",
                "unique_together": {("user", "device_fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Heure de pointage",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude réelle"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude réelle"
                    ),
                ),
                (
                    "distance_meters",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Distance du bureau (mètres)",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Empreinte appareil"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("LATE", "En retard"),
                            ("SUSPICIOUS", "Suspect"),
                            ("FAILED", "Échoué"),
                            ("ABSENT", "Absent"),
                        ],
                        default="PRESENT",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OUT_OF_RANGE", "Hors zone autorisée"),
                            ("DEVICE_MISMATCH", "Appareil non reconnu"),
                            ("DEVICE_CONFLICT", "Appareil utilisé par un autre compte"),
                            ("ALREADY_CHECKED", "Déjà pointé aujourd'hui"),
                            ("GPS_UNAVAILABLE", "GPS indisponible"),
                            ("OUTSIDE_HOURS", "Hors horaires autorisés"),
                        ],
                        max_length=25,
                        verbose_name="Raison d'échec",
                    ),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(
                        default=False,
                        help_text="Signalé automatiquement si le device fingerprint est partagé",
                        verbose_name="Suspect",
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="Note admin")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to="attendance.office",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage",
                "verbose_name_plural": "Pointages",
                "ordering": ["-check_in_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="attendance__user_id_c01e0c_idx"
                    ),
                    models.Index(
                        fields=["date", "status"], name="attendance__date_3889e6_idx"
                    ),
                    models.Index(
                        fields=["device_fingerprint"],
                        name="attendance__device__cf1526_idx",
                    ),
                ],
            },
        ),
    ]
